export {
  DiagramSpecSchema,
  type DiagramSpec,
  type SingleDiagram,
  type DiagramNode,
  type DiagramEdge,
  type NodeStyle,
  type EdgeStyle,
  type NodeSpatial,
  type NodeFont,
  type AnchorSide,
  type ImageDimensions,
  type ColorPaletteEntry,
  type ColorPalette,
  type ShapeKind,
  type ShapePaletteEntry,
  type SizePaletteEntry,
  type SemanticTypeEntry,
  type GuideLine,
  type EdgeLabelStyle,
  type ClockPosition,
  type NodeLabel,
  type EdgeLabel,
  type MarkerKind,
} from "./diagram-spec.js";
