export {
  DiagramSpecSchema,
  type DiagramSpec,
  type SingleDiagram,
  type DiagramNode,
  type DiagramEdge,
  type NodeStyle,
  type EdgeStyle,
  type NodeSpatial,
  type NodeFont,
  type AnchorSide,
  type ImageDimensions,
  type ColorPaletteEntry,
  type ColorPalette,
  type ShapeKind,
  type ShapePaletteEntry,
  type SizePaletteEntry,
  type SemanticTypeEntry,
} from "./diagram-spec.js";
